# Generated by Django 2.2 on 2020-07-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='dessert',
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_dessert',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Desserts',
        ),
    ]
